import type { WizardConfig } from '../types'

/** Healthcare Directive / Advance Directive wizard configuration */
export const healthcareDirectiveWizardConfig: WizardConfig = {
  id: 'healthcare-directive-document',
  title: 'Healthcare Directive',
  description: 'Document your medical wishes and designate someone to make healthcare decisions on your behalf.',
  documentType: 'healthcare-directive',
  steps: [
    {
      id: 'personal-info',
      title: 'Your Information',
      description: 'Tell us about yourself — the person creating this directive.',
      fields: [
        {
          name: 'declarantName',
          label: 'Full Legal Name',
          type: 'text',
          required: true,
          placeholder: 'John Michael Smith',
        },
        {
          name: 'declarantDateOfBirth',
          label: 'Date of Birth',
          type: 'date',
          required: true,
        },
        {
          name: 'declarantAddress',
          label: 'Street Address',
          type: 'text',
          required: true,
          placeholder: '123 Main Street',
        },
        {
          name: 'declarantCity',
          label: 'City',
          type: 'text',
          required: true,
          placeholder: 'San Diego',
        },
        {
          name: 'declarantState',
          label: 'State',
          type: 'select',
          required: true,
          options: stateOptions(),
          helpText: 'Your state determines specific requirements for this document.',
        },
        {
          name: 'declarantZipCode',
          label: 'Zip Code',
          type: 'text',
          required: true,
          placeholder: '92101',
        },
        {
          name: 'declarantCounty',
          label: 'County',
          type: 'text',
          required: true,
          placeholder: 'San Diego',
        },
        {
          name: 'declarantPhone',
          label: 'Phone Number',
          type: 'tel',
          placeholder: '(555) 123-4567',
        },
      ],
    },
    {
      id: 'healthcare-agent',
      title: 'Healthcare Agent',
      description: 'Choose who will make medical decisions on your behalf if you cannot.',
      fields: [
        {
          name: 'agentName',
          label: 'Healthcare Agent — Full Legal Name',
          type: 'text',
          required: true,
          placeholder: 'Jane Elizabeth Smith',
          helpText: 'Also called "healthcare proxy" or "healthcare surrogate" in some states.',
        },
        {
          name: 'agentRelationship',
          label: 'Relationship to You',
          type: 'select',
          required: true,
          options: [
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Parent', value: 'parent' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Other Family Member', value: 'family' },
            { label: 'Friend', value: 'friend' },
          ],
        },
        {
          name: 'agentAddress',
          label: 'Agent\'s Address',
          type: 'text',
          required: true,
          placeholder: '456 Oak Avenue, San Diego, CA 92102',
        },
        {
          name: 'agentPhone',
          label: 'Agent\'s Phone Number',
          type: 'tel',
          required: true,
          placeholder: '(555) 987-6543',
        },
        {
          name: 'agentEmail',
          label: 'Agent\'s Email',
          type: 'email',
          placeholder: 'jane@example.com',
        },
        {
          name: 'hasAlternateAgent',
          label: 'Designate an alternate healthcare agent?',
          type: 'radio',
          required: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          helpText: 'An alternate can act if your primary agent is unavailable.',
        },
        {
          name: 'alternateAgentName',
          label: 'Alternate Agent — Full Legal Name',
          type: 'text',
          placeholder: 'Robert James Smith',
          showWhen: (values) => values.hasAlternateAgent === 'yes',
        },
        {
          name: 'alternateAgentRelationship',
          label: 'Alternate Agent\'s Relationship to You',
          type: 'select',
          options: [
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Parent', value: 'parent' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Other Family Member', value: 'family' },
            { label: 'Friend', value: 'friend' },
          ],
          showWhen: (values) => values.hasAlternateAgent === 'yes',
        },
        {
          name: 'alternateAgentAddress',
          label: 'Alternate Agent\'s Address',
          type: 'text',
          placeholder: '789 Pine Street, San Diego, CA 92103',
          showWhen: (values) => values.hasAlternateAgent === 'yes',
        },
        {
          name: 'alternateAgentPhone',
          label: 'Alternate Agent\'s Phone',
          type: 'tel',
          showWhen: (values) => values.hasAlternateAgent === 'yes',
        },
      ],
    },
    {
      id: 'life-sustaining-treatment',
      title: 'Life-Sustaining Treatment',
      description: 'Express your wishes about medical treatment in critical situations.',
      fields: [
        {
          name: 'lifeSupportPreference',
          label: 'If I am terminally ill with no reasonable hope of recovery:',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want all life-sustaining treatment continued', value: 'continue-all' },
            { label: 'I want life-sustaining treatment stopped and comfort care only', value: 'comfort-only' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
        {
          name: 'permanentUnconsciousPreference',
          label: 'If I am in a permanent vegetative state or irreversible coma:',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want all life-sustaining treatment continued', value: 'continue-all' },
            { label: 'I want life-sustaining treatment withdrawn', value: 'withdraw' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
        {
          name: 'cprPreference',
          label: 'Cardiopulmonary Resuscitation (CPR)',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want CPR attempted', value: 'yes' },
            { label: 'I do not want CPR (DNR — Do Not Resuscitate)', value: 'no' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
        {
          name: 'ventilatorPreference',
          label: 'Mechanical Ventilation (breathing machine)',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want mechanical ventilation if needed', value: 'yes' },
            { label: 'I do not want long-term mechanical ventilation', value: 'no' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
        {
          name: 'feedingTubePreference',
          label: 'Artificial Nutrition and Hydration (feeding tube)',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want artificial nutrition and hydration', value: 'yes' },
            { label: 'I do not want artificial nutrition and hydration if I cannot eat naturally', value: 'no' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
        {
          name: 'dialysisPreference',
          label: 'Dialysis',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want dialysis if needed', value: 'yes' },
            { label: 'I do not want long-term dialysis', value: 'no' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
      ],
    },
    {
      id: 'additional-wishes',
      title: 'Additional Wishes',
      description: 'Share any additional preferences about your medical care.',
      fields: [
        {
          name: 'painManagement',
          label: 'Pain management preferences',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want maximum pain relief even if it may hasten death', value: 'maximum' },
            { label: 'I want pain relief balanced with remaining alert when possible', value: 'balanced' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
        {
          name: 'organDonation',
          label: 'Organ and tissue donation',
          type: 'radio',
          required: true,
          options: [
            { label: 'I want to donate any needed organs and tissues', value: 'all' },
            { label: 'I want to donate specific organs only', value: 'specific' },
            { label: 'I do not want to donate organs or tissues', value: 'none' },
            { label: 'I want my healthcare agent to decide', value: 'agent-decides' },
          ],
        },
        {
          name: 'specificOrgans',
          label: 'Which organs/tissues do you wish to donate?',
          type: 'textarea',
          placeholder: 'e.g., kidneys, corneas, skin...',
          showWhen: (values) => values.organDonation === 'specific',
        },
        {
          name: 'religiousPreferences',
          label: 'Religious or spiritual preferences for medical care',
          type: 'textarea',
          placeholder: 'Any religious or cultural considerations for your medical treatment...',
          helpText: 'Optional. Include any faith-based treatment preferences or restrictions.',
        },
        {
          name: 'endOfLifeLocation',
          label: 'Where would you prefer to receive end-of-life care?',
          type: 'select',
          options: [
            { label: 'At home', value: 'home' },
            { label: 'Hospital', value: 'hospital' },
            { label: 'Hospice facility', value: 'hospice' },
            { label: 'No preference — let my agent decide', value: 'no-preference' },
          ],
        },
        {
          name: 'additionalInstructions',
          label: 'Any additional instructions for your healthcare agent',
          type: 'textarea',
          placeholder: 'Any other wishes, values, or instructions you want your agent to consider...',
          helpText: 'Optional. This can include quality of life values, specific treatments to avoid, or personal wishes.',
        },
      ],
    },
    {
      id: 'primary-physician',
      title: 'Primary Physician',
      description: 'Optionally identify your primary physician for your records.',
      fields: [
        {
          name: 'hasPhysician',
          label: 'Do you want to name a primary physician?',
          type: 'radio',
          required: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'physicianName',
          label: 'Physician\'s Name',
          type: 'text',
          placeholder: 'Dr. Sarah Johnson',
          showWhen: (values) => values.hasPhysician === 'yes',
        },
        {
          name: 'physicianPhone',
          label: 'Physician\'s Phone',
          type: 'tel',
          placeholder: '(555) 456-7890',
          showWhen: (values) => values.hasPhysician === 'yes',
        },
        {
          name: 'physicianAddress',
          label: 'Physician\'s Address / Practice',
          type: 'text',
          placeholder: 'Scripps Memorial Hospital, La Jolla, CA',
          showWhen: (values) => values.hasPhysician === 'yes',
        },
      ],
    },
    {
      id: 'review',
      title: 'Review & Confirm',
      description: 'Review your healthcare preferences before generating your directive.',
      fields: [
        {
          name: 'acknowledgment',
          label: 'I am of sound mind and understand the nature of the decisions documented in this directive. I am making these choices voluntarily.',
          type: 'checkbox',
          required: true,
        },
        {
          name: 'agentAcknowledgment',
          label: 'I have discussed my wishes with my designated healthcare agent and they are aware of their role.',
          type: 'checkbox',
          required: true,
        },
        {
          name: 'legalDisclaimer',
          label: 'I understand this is an informational tool and not a substitute for professional legal or medical advice.',
          type: 'checkbox',
          required: true,
        },
      ],
    },
  ],
}

/** State options for dropdown */
function stateOptions() {
  return [
    { label: 'Alabama', value: 'Alabama' },
    { label: 'Alaska', value: 'Alaska' },
    { label: 'Arizona', value: 'Arizona' },
    { label: 'Arkansas', value: 'Arkansas' },
    { label: 'California', value: 'California' },
    { label: 'Colorado', value: 'Colorado' },
    { label: 'Connecticut', value: 'Connecticut' },
    { label: 'Delaware', value: 'Delaware' },
    { label: 'Florida', value: 'Florida' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Hawaii', value: 'Hawaii' },
    { label: 'Idaho', value: 'Idaho' },
    { label: 'Illinois', value: 'Illinois' },
    { label: 'Indiana', value: 'Indiana' },
    { label: 'Iowa', value: 'Iowa' },
    { label: 'Kansas', value: 'Kansas' },
    { label: 'Kentucky', value: 'Kentucky' },
    { label: 'Louisiana', value: 'Louisiana' },
    { label: 'Maine', value: 'Maine' },
    { label: 'Maryland', value: 'Maryland' },
    { label: 'Massachusetts', value: 'Massachusetts' },
    { label: 'Michigan', value: 'Michigan' },
    { label: 'Minnesota', value: 'Minnesota' },
    { label: 'Mississippi', value: 'Mississippi' },
    { label: 'Missouri', value: 'Missouri' },
    { label: 'Montana', value: 'Montana' },
    { label: 'Nebraska', value: 'Nebraska' },
    { label: 'Nevada', value: 'Nevada' },
    { label: 'New Hampshire', value: 'New Hampshire' },
    { label: 'New Jersey', value: 'New Jersey' },
    { label: 'New Mexico', value: 'New Mexico' },
    { label: 'New York', value: 'New York' },
    { label: 'North Carolina', value: 'North Carolina' },
    { label: 'North Dakota', value: 'North Dakota' },
    { label: 'Ohio', value: 'Ohio' },
    { label: 'Oklahoma', value: 'Oklahoma' },
    { label: 'Oregon', value: 'Oregon' },
    { label: 'Pennsylvania', value: 'Pennsylvania' },
    { label: 'Rhode Island', value: 'Rhode Island' },
    { label: 'South Carolina', value: 'South Carolina' },
    { label: 'South Dakota', value: 'South Dakota' },
    { label: 'Tennessee', value: 'Tennessee' },
    { label: 'Texas', value: 'Texas' },
    { label: 'Utah', value: 'Utah' },
    { label: 'Vermont', value: 'Vermont' },
    { label: 'Virginia', value: 'Virginia' },
    { label: 'Washington', value: 'Washington' },
    { label: 'West Virginia', value: 'West Virginia' },
    { label: 'Wisconsin', value: 'Wisconsin' },
    { label: 'Wyoming', value: 'Wyoming' },
  ]
}
