import type { WizardConfig } from '../types'

/** Power of Attorney wizard configuration */
export const poaWizardConfig: WizardConfig = {
  id: 'poa-document',
  title: 'Power of Attorney',
  description: 'Designate a trusted person to act on your behalf for financial and legal matters.',
  documentType: 'poa',
  steps: [
    {
      id: 'principal-info',
      title: 'Your Information',
      description: 'Tell us about yourself — the person granting power of attorney.',
      fields: [
        {
          name: 'principalName',
          label: 'Full Legal Name',
          type: 'text',
          required: true,
          placeholder: 'John Michael Smith',
        },
        {
          name: 'principalDateOfBirth',
          label: 'Date of Birth',
          type: 'date',
          required: true,
        },
        {
          name: 'principalAddress',
          label: 'Street Address',
          type: 'text',
          required: true,
          placeholder: '123 Main Street',
        },
        {
          name: 'principalCity',
          label: 'City',
          type: 'text',
          required: true,
          placeholder: 'San Diego',
        },
        {
          name: 'principalState',
          label: 'State',
          type: 'select',
          required: true,
          options: stateOptions(),
        },
        {
          name: 'principalZipCode',
          label: 'Zip Code',
          type: 'text',
          required: true,
          placeholder: '92101',
        },
        {
          name: 'principalCounty',
          label: 'County',
          type: 'text',
          required: true,
          placeholder: 'San Diego',
        },
        {
          name: 'principalPhone',
          label: 'Phone Number',
          type: 'tel',
          placeholder: '(555) 123-4567',
        },
        {
          name: 'principalEmail',
          label: 'Email Address',
          type: 'email',
          placeholder: 'john@example.com',
        },
      ],
    },
    {
      id: 'agent-designation',
      title: 'Agent Designation',
      description: 'Choose who will act on your behalf (your "agent" or "attorney-in-fact").',
      fields: [
        {
          name: 'agentName',
          label: 'Primary Agent — Full Legal Name',
          type: 'text',
          required: true,
          placeholder: 'Jane Elizabeth Smith',
          helpText: 'This person will have authority to act on your behalf.',
        },
        {
          name: 'agentRelationship',
          label: 'Relationship to You',
          type: 'select',
          required: true,
          options: [
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Parent', value: 'parent' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Other Family Member', value: 'family' },
            { label: 'Friend', value: 'friend' },
            { label: 'Attorney / Professional', value: 'professional' },
          ],
        },
        {
          name: 'agentAddress',
          label: 'Agent\'s Address',
          type: 'text',
          required: true,
          placeholder: '456 Oak Avenue, San Diego, CA 92102',
        },
        {
          name: 'agentPhone',
          label: 'Agent\'s Phone Number',
          type: 'tel',
          required: true,
          placeholder: '(555) 987-6543',
        },
        {
          name: 'agentEmail',
          label: 'Agent\'s Email',
          type: 'email',
          placeholder: 'jane@example.com',
        },
        {
          name: 'hasAlternateAgent',
          label: 'Designate an alternate agent?',
          type: 'radio',
          required: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          helpText: 'An alternate agent can act if your primary agent is unable or unwilling.',
        },
        {
          name: 'alternateAgentName',
          label: 'Alternate Agent — Full Legal Name',
          type: 'text',
          placeholder: 'Robert James Smith',
          showWhen: (values) => values.hasAlternateAgent === 'yes',
        },
        {
          name: 'alternateAgentRelationship',
          label: 'Alternate Agent\'s Relationship to You',
          type: 'select',
          options: [
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Parent', value: 'parent' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Other Family Member', value: 'family' },
            { label: 'Friend', value: 'friend' },
            { label: 'Attorney / Professional', value: 'professional' },
          ],
          showWhen: (values) => values.hasAlternateAgent === 'yes',
        },
        {
          name: 'alternateAgentAddress',
          label: 'Alternate Agent\'s Address',
          type: 'text',
          placeholder: '789 Pine Street, San Diego, CA 92103',
          showWhen: (values) => values.hasAlternateAgent === 'yes',
        },
      ],
    },
    {
      id: 'powers-granted',
      title: 'Powers Granted',
      description: 'Select which powers you want to grant your agent.',
      fields: [
        {
          name: 'poaType',
          label: 'Type of Power of Attorney',
          type: 'select',
          required: true,
          options: [
            { label: 'General (broad powers over financial and legal matters)', value: 'general' },
            { label: 'Limited (specific powers only)', value: 'limited' },
            { label: 'Durable (remains effective if you become incapacitated)', value: 'durable' },
            { label: 'Springing (takes effect only upon incapacitation)', value: 'springing' },
          ],
          helpText: 'A durable POA is the most common choice for estate planning purposes.',
        },
        {
          name: 'powerRealEstate',
          label: 'Real estate transactions',
          type: 'checkbox',
          helpText: 'Buy, sell, lease, manage, or mortgage real property.',
        },
        {
          name: 'powerBanking',
          label: 'Banking and financial transactions',
          type: 'checkbox',
          helpText: 'Access accounts, make deposits/withdrawals, manage investments.',
        },
        {
          name: 'powerTax',
          label: 'Tax matters',
          type: 'checkbox',
          helpText: 'File returns, make elections, interact with the IRS on your behalf.',
        },
        {
          name: 'powerInsurance',
          label: 'Insurance and annuities',
          type: 'checkbox',
          helpText: 'Purchase, modify, or claim on insurance policies.',
        },
        {
          name: 'powerRetirement',
          label: 'Retirement plans',
          type: 'checkbox',
          helpText: 'Manage 401(k), IRA, and pension accounts.',
        },
        {
          name: 'powerBusiness',
          label: 'Business operations',
          type: 'checkbox',
          helpText: 'Manage or operate business interests on your behalf.',
        },
        {
          name: 'powerGovernment',
          label: 'Government benefits',
          type: 'checkbox',
          helpText: 'Apply for or manage Social Security, Medicare, Medicaid, and other benefits.',
        },
        {
          name: 'powerLegal',
          label: 'Legal claims and litigation',
          type: 'checkbox',
          helpText: 'File lawsuits, settle claims, hire attorneys.',
        },
        {
          name: 'powerGifting',
          label: 'Gifting authority',
          type: 'checkbox',
          helpText: 'Make gifts on your behalf (subject to annual limits).',
        },
        {
          name: 'powerDigital',
          label: 'Digital assets',
          type: 'checkbox',
          helpText: 'Access and manage online accounts, digital property, cryptocurrency.',
        },
        {
          name: 'limitedPowersDescription',
          label: 'Describe the specific powers granted',
          type: 'textarea',
          placeholder: 'Describe the specific, limited powers you want to grant...',
          showWhen: (values) => values.poaType === 'limited',
          helpText: 'Be as specific as possible about what your agent can and cannot do.',
        },
      ],
    },
    {
      id: 'restrictions',
      title: 'Restrictions & Conditions',
      description: 'Set any limitations on your agent\'s authority.',
      fields: [
        {
          name: 'effectiveDate',
          label: 'When should this POA take effect?',
          type: 'select',
          required: true,
          options: [
            { label: 'Immediately upon signing', value: 'immediate' },
            { label: 'Only upon my incapacitation (springing)', value: 'springing' },
            { label: 'On a specific date', value: 'specific-date' },
          ],
        },
        {
          name: 'effectiveSpecificDate',
          label: 'Effective Date',
          type: 'date',
          showWhen: (values) => values.effectiveDate === 'specific-date',
        },
        {
          name: 'hasExpirationDate',
          label: 'Should this POA expire?',
          type: 'radio',
          required: true,
          options: [
            { label: 'No — remains effective until revoked or death', value: 'no' },
            { label: 'Yes — expires on a specific date', value: 'yes' },
          ],
        },
        {
          name: 'expirationDate',
          label: 'Expiration Date',
          type: 'date',
          showWhen: (values) => values.hasExpirationDate === 'yes',
        },
        {
          name: 'additionalRestrictions',
          label: 'Additional restrictions or instructions',
          type: 'textarea',
          placeholder: 'Any specific restrictions, dollar limits, or instructions for your agent...',
          helpText: 'Optional. For example: "Agent may not sell the family home" or "Gifting limited to $17,000/year per person."',
        },
        {
          name: 'compensationAllowed',
          label: 'Is your agent entitled to compensation?',
          type: 'radio',
          required: true,
          options: [
            { label: 'No — serves without compensation', value: 'no' },
            { label: 'Yes — reasonable compensation', value: 'yes' },
          ],
        },
      ],
    },
    {
      id: 'review',
      title: 'Review & Confirm',
      description: 'Review your selections before generating your Power of Attorney document.',
      fields: [
        {
          name: 'acknowledgment',
          label: 'I understand this document grants significant authority to my designated agent and I am creating it voluntarily.',
          type: 'checkbox',
          required: true,
        },
        {
          name: 'legalDisclaimer',
          label: 'I understand this is an informational tool and not a substitute for professional legal advice. I am encouraged to have an attorney review my documents.',
          type: 'checkbox',
          required: true,
        },
      ],
    },
  ],
}

/** State options for dropdown */
function stateOptions() {
  return [
    { label: 'Alabama', value: 'Alabama' },
    { label: 'Alaska', value: 'Alaska' },
    { label: 'Arizona', value: 'Arizona' },
    { label: 'Arkansas', value: 'Arkansas' },
    { label: 'California', value: 'California' },
    { label: 'Colorado', value: 'Colorado' },
    { label: 'Connecticut', value: 'Connecticut' },
    { label: 'Delaware', value: 'Delaware' },
    { label: 'Florida', value: 'Florida' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Hawaii', value: 'Hawaii' },
    { label: 'Idaho', value: 'Idaho' },
    { label: 'Illinois', value: 'Illinois' },
    { label: 'Indiana', value: 'Indiana' },
    { label: 'Iowa', value: 'Iowa' },
    { label: 'Kansas', value: 'Kansas' },
    { label: 'Kentucky', value: 'Kentucky' },
    { label: 'Louisiana', value: 'Louisiana' },
    { label: 'Maine', value: 'Maine' },
    { label: 'Maryland', value: 'Maryland' },
    { label: 'Massachusetts', value: 'Massachusetts' },
    { label: 'Michigan', value: 'Michigan' },
    { label: 'Minnesota', value: 'Minnesota' },
    { label: 'Mississippi', value: 'Mississippi' },
    { label: 'Missouri', value: 'Missouri' },
    { label: 'Montana', value: 'Montana' },
    { label: 'Nebraska', value: 'Nebraska' },
    { label: 'Nevada', value: 'Nevada' },
    { label: 'New Hampshire', value: 'New Hampshire' },
    { label: 'New Jersey', value: 'New Jersey' },
    { label: 'New Mexico', value: 'New Mexico' },
    { label: 'New York', value: 'New York' },
    { label: 'North Carolina', value: 'North Carolina' },
    { label: 'North Dakota', value: 'North Dakota' },
    { label: 'Ohio', value: 'Ohio' },
    { label: 'Oklahoma', value: 'Oklahoma' },
    { label: 'Oregon', value: 'Oregon' },
    { label: 'Pennsylvania', value: 'Pennsylvania' },
    { label: 'Rhode Island', value: 'Rhode Island' },
    { label: 'South Carolina', value: 'South Carolina' },
    { label: 'South Dakota', value: 'South Dakota' },
    { label: 'Tennessee', value: 'Tennessee' },
    { label: 'Texas', value: 'Texas' },
    { label: 'Utah', value: 'Utah' },
    { label: 'Vermont', value: 'Vermont' },
    { label: 'Virginia', value: 'Virginia' },
    { label: 'Washington', value: 'Washington' },
    { label: 'West Virginia', value: 'West Virginia' },
    { label: 'Wisconsin', value: 'Wisconsin' },
    { label: 'Wyoming', value: 'Wyoming' },
  ]
}
