import type { WizardConfig } from '../types'

/** Trust document wizard configuration */
export const trustWizardConfig: WizardConfig = {
  id: 'trust-document',
  title: 'Living Trust',
  description: 'Create a revocable or irrevocable living trust to manage and protect your assets.',
  documentType: 'trust',
  steps: [
    {
      id: 'grantor-info',
      title: 'Grantor Information',
      description: 'Tell us about yourself — the person creating the trust.',
      fields: [
        {
          name: 'grantorName',
          label: 'Full Legal Name',
          type: 'text',
          required: true,
          placeholder: 'John Michael Smith',
        },
        {
          name: 'grantorDateOfBirth',
          label: 'Date of Birth',
          type: 'date',
          required: true,
        },
        {
          name: 'grantorAddress',
          label: 'Street Address',
          type: 'text',
          required: true,
          placeholder: '123 Main Street',
        },
        {
          name: 'grantorCity',
          label: 'City',
          type: 'text',
          required: true,
          placeholder: 'San Diego',
        },
        {
          name: 'grantorState',
          label: 'State',
          type: 'select',
          required: true,
          options: stateOptions(),
        },
        {
          name: 'grantorZipCode',
          label: 'Zip Code',
          type: 'text',
          required: true,
          placeholder: '92101',
        },
        {
          name: 'grantorCounty',
          label: 'County',
          type: 'text',
          required: true,
          placeholder: 'San Diego',
        },
        {
          name: 'grantorEmail',
          label: 'Email Address',
          type: 'email',
          required: true,
          placeholder: 'john@example.com',
        },
        {
          name: 'grantorPhone',
          label: 'Phone Number',
          type: 'tel',
          placeholder: '(555) 123-4567',
        },
        {
          name: 'maritalStatus',
          label: 'Marital Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Single', value: 'single' },
            { label: 'Married', value: 'married' },
            { label: 'Domestic Partnership', value: 'domestic-partnership' },
            { label: 'Divorced', value: 'divorced' },
            { label: 'Widowed', value: 'widowed' },
          ],
        },
        {
          name: 'isJointTrust',
          label: 'Do you want to create a joint trust with your spouse?',
          type: 'radio',
          options: [
            { label: 'Yes — joint trust with my spouse', value: 'yes' },
            { label: 'No — individual trust', value: 'no' },
          ],
          showWhen: (values) =>
            values.maritalStatus === 'married' || values.maritalStatus === 'domestic-partnership',
        },
        {
          name: 'spouseName',
          label: 'Spouse / Partner\'s Full Legal Name',
          type: 'text',
          placeholder: 'Jane Elizabeth Smith',
          showWhen: (values) => values.isJointTrust === 'yes',
        },
        {
          name: 'spouseAddress',
          label: 'Spouse\'s Address (if different)',
          type: 'text',
          placeholder: 'Leave blank if same address',
          showWhen: (values) => values.isJointTrust === 'yes',
        },
      ],
    },
    {
      id: 'trust-type',
      title: 'Trust Type',
      description: 'Choose the type of trust that best fits your needs.',
      fields: [
        {
          name: 'trustType',
          label: 'Type of Trust',
          type: 'radio',
          required: true,
          options: [
            { label: 'Revocable Living Trust — you can modify or revoke it during your lifetime', value: 'revocable' },
            { label: 'Irrevocable Living Trust — cannot be changed once established (stronger asset protection)', value: 'irrevocable' },
          ],
          helpText: 'A revocable trust is the most common choice. It avoids probate while letting you maintain control.',
        },
        {
          name: 'trustName',
          label: 'Trust Name',
          type: 'text',
          required: true,
          placeholder: 'The Smith Family Trust',
          helpText: 'Typically "[Your Last Name] Family Trust" or "[Your Name] Living Trust".',
        },
        {
          name: 'hasMinorChildren',
          label: 'Do you have minor children (under 18)?',
          type: 'radio',
          required: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'minorChildrenDistributionAge',
          label: 'At what age should minor children receive their full share?',
          type: 'select',
          options: [
            { label: '18 years old', value: '18' },
            { label: '21 years old', value: '21' },
            { label: '25 years old', value: '25' },
            { label: '30 years old', value: '30' },
            { label: '35 years old', value: '35' },
          ],
          showWhen: (values) => values.hasMinorChildren === 'yes',
          helpText: 'Until this age, the trustee manages their share for education, health, and support.',
        },
      ],
    },
    {
      id: 'trustees',
      title: 'Trustees',
      description: 'Choose who will manage the trust — during your lifetime and after.',
      fields: [
        {
          name: 'initialTrusteeName',
          label: 'Initial Trustee',
          type: 'text',
          required: true,
          helpText: 'Usually you are the initial trustee of your own revocable trust. Enter your name.',
          placeholder: 'John Michael Smith',
        },
        {
          name: 'initialTrusteeAddress',
          label: 'Initial Trustee\'s Address',
          type: 'text',
          required: true,
          placeholder: '123 Main Street, San Diego, CA 92101',
        },
        {
          name: 'initialTrusteeRelationship',
          label: 'Relationship',
          type: 'select',
          required: true,
          options: [
            { label: 'Self', value: 'self' },
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Other Family Member', value: 'family' },
            { label: 'Attorney / Professional', value: 'professional' },
            { label: 'Corporate Trustee / Bank', value: 'corporate' },
          ],
        },
        {
          name: 'successorTrusteeName',
          label: 'Successor Trustee',
          type: 'text',
          required: true,
          placeholder: 'Jane Elizabeth Smith',
          helpText: 'This person takes over if you can no longer serve (incapacity or death).',
        },
        {
          name: 'successorTrusteeAddress',
          label: 'Successor Trustee\'s Address',
          type: 'text',
          required: true,
          placeholder: '456 Oak Avenue, San Diego, CA 92102',
        },
        {
          name: 'successorTrusteeRelationship',
          label: 'Successor Trustee\'s Relationship',
          type: 'select',
          required: true,
          options: [
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Other Family Member', value: 'family' },
            { label: 'Friend', value: 'friend' },
            { label: 'Attorney / Professional', value: 'professional' },
            { label: 'Corporate Trustee / Bank', value: 'corporate' },
          ],
        },
        {
          name: 'hasSecondSuccessor',
          label: 'Designate a second successor trustee?',
          type: 'radio',
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'secondSuccessorTrusteeName',
          label: 'Second Successor Trustee',
          type: 'text',
          placeholder: 'Robert James Smith',
          showWhen: (values) => values.hasSecondSuccessor === 'yes',
        },
        {
          name: 'secondSuccessorTrusteeAddress',
          label: 'Second Successor Trustee\'s Address',
          type: 'text',
          showWhen: (values) => values.hasSecondSuccessor === 'yes',
        },
      ],
    },
    {
      id: 'beneficiaries',
      title: 'Beneficiaries',
      description: 'Decide who receives the trust assets after your passing.',
      fields: [
        {
          name: 'primaryBeneficiary1Name',
          label: 'Primary Beneficiary #1 — Name',
          type: 'text',
          required: true,
          placeholder: 'Jane Elizabeth Smith',
        },
        {
          name: 'primaryBeneficiary1Relationship',
          label: 'Relationship',
          type: 'select',
          required: true,
          options: relationshipOptions(),
        },
        {
          name: 'primaryBeneficiary1Percentage',
          label: 'Percentage of Trust Estate',
          type: 'number',
          required: true,
          placeholder: '50',
          helpText: 'Enter a number (e.g., 50 for 50%). All primary beneficiaries should total 100%.',
        },
        {
          name: 'hasSecondBeneficiary',
          label: 'Add another primary beneficiary?',
          type: 'radio',
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'primaryBeneficiary2Name',
          label: 'Primary Beneficiary #2 — Name',
          type: 'text',
          placeholder: 'Robert James Smith',
          showWhen: (values) => values.hasSecondBeneficiary === 'yes',
        },
        {
          name: 'primaryBeneficiary2Relationship',
          label: 'Relationship',
          type: 'select',
          options: relationshipOptions(),
          showWhen: (values) => values.hasSecondBeneficiary === 'yes',
        },
        {
          name: 'primaryBeneficiary2Percentage',
          label: 'Percentage of Trust Estate',
          type: 'number',
          placeholder: '50',
          showWhen: (values) => values.hasSecondBeneficiary === 'yes',
        },
        {
          name: 'hasThirdBeneficiary',
          label: 'Add a third primary beneficiary?',
          type: 'radio',
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          showWhen: (values) => values.hasSecondBeneficiary === 'yes',
        },
        {
          name: 'primaryBeneficiary3Name',
          label: 'Primary Beneficiary #3 — Name',
          type: 'text',
          showWhen: (values) => values.hasThirdBeneficiary === 'yes',
        },
        {
          name: 'primaryBeneficiary3Relationship',
          label: 'Relationship',
          type: 'select',
          options: relationshipOptions(),
          showWhen: (values) => values.hasThirdBeneficiary === 'yes',
        },
        {
          name: 'primaryBeneficiary3Percentage',
          label: 'Percentage of Trust Estate',
          type: 'number',
          showWhen: (values) => values.hasThirdBeneficiary === 'yes',
        },
        {
          name: 'hasContingentBeneficiary',
          label: 'Add a contingent beneficiary (receives assets if primary beneficiaries predecease you)?',
          type: 'radio',
          required: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'contingentBeneficiaryName',
          label: 'Contingent Beneficiary — Name',
          type: 'text',
          showWhen: (values) => values.hasContingentBeneficiary === 'yes',
        },
        {
          name: 'contingentBeneficiaryRelationship',
          label: 'Contingent Beneficiary — Relationship',
          type: 'select',
          options: relationshipOptions(),
          showWhen: (values) => values.hasContingentBeneficiary === 'yes',
        },
        {
          name: 'contingentBeneficiaryPercentage',
          label: 'Contingent Beneficiary — Percentage',
          type: 'number',
          placeholder: '100',
          showWhen: (values) => values.hasContingentBeneficiary === 'yes',
        },
      ],
    },
    {
      id: 'trust-assets',
      title: 'Trust Assets',
      description: 'List the assets you want to transfer into the trust.',
      fields: [
        {
          name: 'hasRealEstate',
          label: 'Real Estate / Property',
          type: 'checkbox',
          helpText: 'Homes, land, rental properties, commercial property.',
        },
        {
          name: 'realEstateDescription',
          label: 'Describe your real estate',
          type: 'textarea',
          placeholder: 'Primary residence at 123 Main St, San Diego, CA 92101\nRental property at 456 Oak Ave, San Diego, CA 92102',
          showWhen: (values) => values.hasRealEstate === true,
          helpText: 'Include addresses and approximate values if known.',
        },
        {
          name: 'hasBankAccounts',
          label: 'Bank Accounts',
          type: 'checkbox',
          helpText: 'Checking, savings, CDs, money market accounts.',
        },
        {
          name: 'bankAccountsDescription',
          label: 'Describe your bank accounts',
          type: 'textarea',
          placeholder: 'Chase checking account ending in 1234\nWells Fargo savings account ending in 5678',
          showWhen: (values) => values.hasBankAccounts === true,
        },
        {
          name: 'hasInvestments',
          label: 'Investment Accounts',
          type: 'checkbox',
          helpText: 'Brokerage accounts, stocks, bonds, mutual funds (not retirement accounts).',
        },
        {
          name: 'investmentsDescription',
          label: 'Describe your investments',
          type: 'textarea',
          placeholder: 'Fidelity brokerage account ending in 9012',
          showWhen: (values) => values.hasInvestments === true,
        },
        {
          name: 'hasVehicles',
          label: 'Vehicles',
          type: 'checkbox',
          helpText: 'Cars, boats, RVs, motorcycles.',
        },
        {
          name: 'vehiclesDescription',
          label: 'Describe your vehicles',
          type: 'textarea',
          placeholder: '2022 Tesla Model Y\n2019 Toyota Camry',
          showWhen: (values) => values.hasVehicles === true,
        },
        {
          name: 'hasPersonalProperty',
          label: 'Personal Property',
          type: 'checkbox',
          helpText: 'Jewelry, art, collectibles, furniture, and other valuable items.',
        },
        {
          name: 'personalPropertyDescription',
          label: 'Describe personal property to include',
          type: 'textarea',
          placeholder: 'Family jewelry collection\nArt collection',
          showWhen: (values) => values.hasPersonalProperty === true,
        },
        {
          name: 'hasBusinessInterests',
          label: 'Business Interests',
          type: 'checkbox',
          helpText: 'LLC memberships, partnership interests, sole proprietorships.',
        },
        {
          name: 'businessDescription',
          label: 'Describe your business interests',
          type: 'textarea',
          placeholder: '50% ownership of Smith Consulting LLC',
          showWhen: (values) => values.hasBusinessInterests === true,
        },
        {
          name: 'hasOtherAssets',
          label: 'Other Assets',
          type: 'checkbox',
        },
        {
          name: 'otherAssetsDescription',
          label: 'Describe other assets',
          type: 'textarea',
          placeholder: 'Digital assets, cryptocurrency, intellectual property...',
          showWhen: (values) => values.hasOtherAssets === true,
        },
      ],
    },
    {
      id: 'special-provisions',
      title: 'Special Provisions',
      description: 'Add any special instructions or provisions to your trust.',
      fields: [
        {
          name: 'hasSpecialProvisions',
          label: 'Do you want to include special provisions?',
          type: 'radio',
          required: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No — use standard provisions', value: 'no' },
          ],
        },
        {
          name: 'specialProvisions',
          label: 'Special Provisions',
          type: 'textarea',
          placeholder: 'Any specific instructions for asset management or distribution...',
          showWhen: (values) => values.hasSpecialProvisions === 'yes',
          helpText: 'For example: "My home shall not be sold during my spouse\'s lifetime" or "Education expenses for grandchildren shall be paid from the trust."',
        },
        {
          name: 'charitableGiving',
          label: 'Include charitable giving provisions?',
          type: 'radio',
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'charityName',
          label: 'Charity / Organization Name',
          type: 'text',
          placeholder: 'American Red Cross',
          showWhen: (values) => values.charitableGiving === 'yes',
        },
        {
          name: 'charityAmount',
          label: 'Amount or Percentage',
          type: 'text',
          placeholder: '$10,000 or 5% of trust estate',
          showWhen: (values) => values.charitableGiving === 'yes',
        },
        {
          name: 'petProvisions',
          label: 'Include provisions for pet care?',
          type: 'radio',
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'petCaretaker',
          label: 'Designated Pet Caretaker',
          type: 'text',
          placeholder: 'Name of person who will care for your pets',
          showWhen: (values) => values.petProvisions === 'yes',
        },
        {
          name: 'petCareAmount',
          label: 'Amount set aside for pet care',
          type: 'text',
          placeholder: '$5,000',
          showWhen: (values) => values.petProvisions === 'yes',
        },
      ],
    },
    {
      id: 'review',
      title: 'Review & Confirm',
      description: 'Review your trust details before generating the document.',
      fields: [
        {
          name: 'acknowledgment',
          label: 'I understand that creating a trust requires transferring assets into the trust after signing. The trust document alone does not transfer ownership.',
          type: 'checkbox',
          required: true,
        },
        {
          name: 'fundingReminder',
          label: 'I understand I will need to retitle assets (real estate deeds, bank accounts, etc.) in the name of the trust to complete the process.',
          type: 'checkbox',
          required: true,
        },
        {
          name: 'legalDisclaimer',
          label: 'I understand this is an informational tool and not a substitute for professional legal advice. I am encouraged to have an attorney review my trust documents.',
          type: 'checkbox',
          required: true,
        },
      ],
    },
  ],
}

/** Relationship options for beneficiary fields */
function relationshipOptions() {
  return [
    { label: 'Spouse / Partner', value: 'spouse' },
    { label: 'Child', value: 'child' },
    { label: 'Grandchild', value: 'grandchild' },
    { label: 'Parent', value: 'parent' },
    { label: 'Sibling', value: 'sibling' },
    { label: 'Niece / Nephew', value: 'niece-nephew' },
    { label: 'Other Family Member', value: 'family' },
    { label: 'Friend', value: 'friend' },
    { label: 'Charity / Organization', value: 'charity' },
  ]
}

/** State options for dropdown */
function stateOptions() {
  return [
    { label: 'Alabama', value: 'Alabama' },
    { label: 'Alaska', value: 'Alaska' },
    { label: 'Arizona', value: 'Arizona' },
    { label: 'Arkansas', value: 'Arkansas' },
    { label: 'California', value: 'California' },
    { label: 'Colorado', value: 'Colorado' },
    { label: 'Connecticut', value: 'Connecticut' },
    { label: 'Delaware', value: 'Delaware' },
    { label: 'Florida', value: 'Florida' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Hawaii', value: 'Hawaii' },
    { label: 'Idaho', value: 'Idaho' },
    { label: 'Illinois', value: 'Illinois' },
    { label: 'Indiana', value: 'Indiana' },
    { label: 'Iowa', value: 'Iowa' },
    { label: 'Kansas', value: 'Kansas' },
    { label: 'Kentucky', value: 'Kentucky' },
    { label: 'Louisiana', value: 'Louisiana' },
    { label: 'Maine', value: 'Maine' },
    { label: 'Maryland', value: 'Maryland' },
    { label: 'Massachusetts', value: 'Massachusetts' },
    { label: 'Michigan', value: 'Michigan' },
    { label: 'Minnesota', value: 'Minnesota' },
    { label: 'Mississippi', value: 'Mississippi' },
    { label: 'Missouri', value: 'Missouri' },
    { label: 'Montana', value: 'Montana' },
    { label: 'Nebraska', value: 'Nebraska' },
    { label: 'Nevada', value: 'Nevada' },
    { label: 'New Hampshire', value: 'New Hampshire' },
    { label: 'New Jersey', value: 'New Jersey' },
    { label: 'New Mexico', value: 'New Mexico' },
    { label: 'New York', value: 'New York' },
    { label: 'North Carolina', value: 'North Carolina' },
    { label: 'North Dakota', value: 'North Dakota' },
    { label: 'Ohio', value: 'Ohio' },
    { label: 'Oklahoma', value: 'Oklahoma' },
    { label: 'Oregon', value: 'Oregon' },
    { label: 'Pennsylvania', value: 'Pennsylvania' },
    { label: 'Rhode Island', value: 'Rhode Island' },
    { label: 'South Carolina', value: 'South Carolina' },
    { label: 'South Dakota', value: 'South Dakota' },
    { label: 'Tennessee', value: 'Tennessee' },
    { label: 'Texas', value: 'Texas' },
    { label: 'Utah', value: 'Utah' },
    { label: 'Vermont', value: 'Vermont' },
    { label: 'Virginia', value: 'Virginia' },
    { label: 'Washington', value: 'Washington' },
    { label: 'West Virginia', value: 'West Virginia' },
    { label: 'Wisconsin', value: 'Wisconsin' },
    { label: 'Wyoming', value: 'Wyoming' },
  ]
}
