import type { WizardConfig } from '../types'

/** Will document wizard configuration */
export const willWizardConfig: WizardConfig = {
  id: 'will-document',
  title: 'Last Will & Testament',
  description: 'Create your legally binding will in a few simple steps.',
  documentType: 'will',
  steps: [
    {
      id: 'personal-info',
      title: 'Personal Info',
      description: 'Tell us about yourself so we can prepare your document.',
      fields: [
        {
          name: 'fullName',
          label: 'Full Legal Name',
          type: 'text',
          required: true,
          placeholder: 'John Michael Smith',
        },
        {
          name: 'dateOfBirth',
          label: 'Date of Birth',
          type: 'date',
          required: true,
        },
        {
          name: 'email',
          label: 'Email Address',
          type: 'email',
          required: true,
          placeholder: 'john@example.com',
        },
        {
          name: 'phone',
          label: 'Phone Number',
          type: 'tel',
          placeholder: '(555) 123-4567',
        },
        {
          name: 'address',
          label: 'Home Address',
          type: 'textarea',
          required: true,
          placeholder: '123 Main St\nSan Diego, CA 92101',
        },
        {
          name: 'maritalStatus',
          label: 'Marital Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Single', value: 'single' },
            { label: 'Married', value: 'married' },
            { label: 'Domestic Partnership', value: 'domestic-partnership' },
            { label: 'Divorced', value: 'divorced' },
            { label: 'Widowed', value: 'widowed' },
          ],
        },
        {
          name: 'spouseName',
          label: 'Spouse / Partner Name',
          type: 'text',
          placeholder: 'Jane Smith',
          showWhen: (values) =>
            values.maritalStatus === 'married' || values.maritalStatus === 'domestic-partnership',
        },
      ],
    },
    {
      id: 'beneficiaries',
      title: 'Beneficiaries',
      description: 'Who will receive your assets?',
      fields: [
        {
          name: 'primaryBeneficiary',
          label: 'Primary Beneficiary',
          type: 'text',
          required: true,
          placeholder: 'Full name of primary beneficiary',
          helpText: 'This person will inherit the majority of your estate.',
        },
        {
          name: 'primaryRelationship',
          label: 'Relationship to You',
          type: 'select',
          required: true,
          options: [
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Parent', value: 'parent' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Other Family', value: 'other-family' },
            { label: 'Friend', value: 'friend' },
            { label: 'Charity / Organization', value: 'charity' },
          ],
        },
        {
          name: 'secondaryBeneficiary',
          label: 'Secondary Beneficiary (Optional)',
          type: 'text',
          placeholder: 'Full name of alternate beneficiary',
          helpText: 'If the primary beneficiary cannot inherit, this person will.',
        },
        {
          name: 'specificBequests',
          label: 'Specific Bequests',
          type: 'textarea',
          placeholder: 'e.g., "My wedding ring to my daughter Sarah"',
          helpText: 'List any specific items you want to leave to specific people.',
        },
      ],
    },
    {
      id: 'executor',
      title: 'Executor',
      description: 'Choose who will carry out the terms of your will.',
      fields: [
        {
          name: 'executorName',
          label: 'Executor Name',
          type: 'text',
          required: true,
          placeholder: 'Full name of your chosen executor',
          helpText: 'This person will manage your estate and distribute assets according to your will.',
        },
        {
          name: 'executorRelationship',
          label: 'Relationship to You',
          type: 'select',
          required: true,
          options: [
            { label: 'Spouse / Partner', value: 'spouse' },
            { label: 'Child', value: 'child' },
            { label: 'Parent', value: 'parent' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Friend', value: 'friend' },
            { label: 'Attorney', value: 'attorney' },
            { label: 'Other', value: 'other' },
          ],
        },
        {
          name: 'executorPhone',
          label: 'Executor Phone',
          type: 'tel',
          placeholder: '(555) 123-4567',
        },
        {
          name: 'executorEmail',
          label: 'Executor Email',
          type: 'email',
          placeholder: 'executor@example.com',
        },
        {
          name: 'alternateExecutor',
          label: 'Alternate Executor (Optional)',
          type: 'text',
          placeholder: 'Full name of backup executor',
          helpText: 'If your primary executor cannot serve, this person will take over.',
        },
      ],
    },
    {
      id: 'guardianship',
      title: 'Guardianship',
      description: 'If you have minor children, designate who will care for them.',
      fields: [
        {
          name: 'hasMinorChildren',
          label: 'Do you have minor children?',
          type: 'radio',
          required: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
        },
        {
          name: 'guardianName',
          label: 'Guardian Name',
          type: 'text',
          required: true,
          placeholder: 'Full name of chosen guardian',
          showWhen: (values) => values.hasMinorChildren === 'yes',
        },
        {
          name: 'guardianRelationship',
          label: 'Relationship to Children',
          type: 'select',
          options: [
            { label: 'Grandparent', value: 'grandparent' },
            { label: 'Aunt / Uncle', value: 'aunt-uncle' },
            { label: 'Sibling', value: 'sibling' },
            { label: 'Close Friend', value: 'friend' },
            { label: 'Other', value: 'other' },
          ],
          showWhen: (values) => values.hasMinorChildren === 'yes',
        },
        {
          name: 'alternateGuardian',
          label: 'Alternate Guardian (Optional)',
          type: 'text',
          placeholder: 'Full name of backup guardian',
          showWhen: (values) => values.hasMinorChildren === 'yes',
        },
      ],
    },
    {
      id: 'review',
      title: 'Review & Sign',
      description: 'Review your information before finalizing your will.',
      fields: [
        {
          name: 'reviewConfirmation',
          label: 'I confirm that all information provided is accurate and complete.',
          type: 'checkbox',
          required: true,
        },
        {
          name: 'signatureAcknowledgment',
          label: 'I understand this document will need to be printed, signed, and witnessed according to my state\'s laws.',
          type: 'checkbox',
          required: true,
        },
      ],
    },
  ],
}
